import "@/../styles/globals.css";
import { Audiowide } from "next/font/google";
import { ReactNode } from "react";
import Navbar from "@/components/SIGNLE-USE/Navbar/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import DontRenderWhen from "@/components/REUSABLE/DontRenderWhen/DontRenderWhen";
import PlayPanel from "@/components/SIGNLE-USE/PlayPanel/PlayPanel";

const audiowide = Audiowide({ subsets: ["latin"], weight: ["400"] });
export const metadata = {
  title: "web-player",
  description: "Generated by Shadow",
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider
    // publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body className={audiowide.className}>
          <DontRenderWhen route={["/login", "/upload"]}>
            <Navbar />
          </DontRenderWhen>
          {children}
          <DontRenderWhen route={["/login", "/upload"]}>
            <PlayPanel />
          </DontRenderWhen>
        </body>
      </html>
    </ClerkProvider>
  );
}
