import "@/../styles/globals.css";
import { Audiowide } from "next/font/google";
import { ReactNode } from "react";
import Navbar from "@/components/REUSABLE/Navbar/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const audiowide = Audiowide({ subsets: ["latin"], weight: ["400"] });
export const metadata = {
  title: "web-player",
  description: "Generated by Shadow",
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider
    // publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body className={audiowide.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
