import { Inter } from "next/font/google";
import "@/../styles/globals.css";
import { ReactNode } from "react";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "web-player",
  description: "Generated by Shadow",
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
